### ISSUE TITLE
Migrate ESGF Users to CoG Accounts

### ISSUE THREAD

**Issue by murphysj** [EarthSystemCoG/COG#1002]
WHO: Luca

**Comment by LucaCinquini** [comment]
It turns out that there is nothing to do to migrate user accounts for a newly created CoG node because:

1) If a user has an existing ESGF account, they can use their existing OpenID to log onto CoG. Upon their first login, they will be asked for a few pieces of missing information to complete their CoG profile (country and institution), after which a CoG account will be automatically created.

2) If a user creates a new CoG account, their information will be automatically transferred to the database of the local ESGF node. In particular, a new OpenID will be created for them, which they can use to log onto the local ESGF IdP and CoG instance.

**Comment by LucaCinquini** [comment]
I have inserted this information into a new page:
https://www.earthsystemcog.org/projects/cog/user_accounts
Sylvia can you please review and close the ticket - I have verified the functionality again.

At some point we might want to have a summary document called "ESGF Migration Guide" which references all these shorter pages.

**Comment by murphysj** [comment]
changed the title a bit to reflect the true content. User accounts is too broad and won't don't really cover everything associated with it. 

Closing.
