### ISSUE TITLE
Fix permissions on files on the CU server

### ISSUE THREAD

**Issue by murphysj** [EarthSystemCoG/COG#1010]
WHO: Sylvia

Deleting files from the server is resulting a serve error. The permissions on the files are screwed up. Some are owned by nobody. Some are owned by DWC.

**Comment by murphysj** [comment]
sylvia to identify several files we want to delete.

Luca, will turn on debug early in the morning

try to see the full error message

**Comment by murphysj** [comment]
These are files that can be deleted.


https://www.earthsystemcog.org/site_media/projects/cog/news_widget.jpg
https://www.earthsystemcog.org/site_media/projects/cog/comments.png
https://www.earthsystemcog.org/site_media/projects/cog/joinProject.png
https://www.earthsystemcog.org/site_media/projects/cog/leftnav.png
https://www.earthsystemcog.org/site_media/projects/cog/sample_cv_small.png

**Comment by LucaCinquini** [comment]
The problem was that the system path for these files was wrong:
data/web/projects/cog_cu/COG/site_media/cog/news_widget.jpg
instead of:
data/web/projects/cog_cu/COG/site_media/projects/cog/news_widget.jpg

clearly a remnant of when the location of the attachments was moved one directory down.
Now CoG will try both locations when deleting files from the system.
 
Sylvia - you could try to test this ticket on dev-hydra, but you might just need to wait to try after this release is deployed at CU.

**Comment by murphysj** [comment]
Agree, we need to test this on the production server. I have made a note for myself. I close this then.
