### ISSUE TITLE
Deal with the creation of "openiduser#" usernames

### ISSUE THREAD

**Issue by murphysj** [EarthSystemCoG/COG#1025]
WHO: Sylvia

If a user has a preexisting ESGF openid and they use it to login in to cog, cog should grab the username from their account. 

Some IDPs don't provide the user name and cog is assigning them one called "openiduser" with a number. 

We are having to change these manually. 

Find some why do deal with these in an automated way.

**Comment by murphysj** [comment]
@LucaCinquini 

While it is true that we can manually change these in the Django Admin interface, the user would  have to be notified. 

Is one option to prohibit users from using ESGF openids from IdPs that turn off username sharing...e.g. force ESGF to share this?

**Comment by murphysj** [comment]
On #1187 Luca says he is going to try and find a solution for new accounts and we can manually update existing account. There are not that many.

**Comment by LucaCinquini** [comment]
No we cannot ban users from the UK - they are one of the most important ESGF institutions.

**Comment by LucaCinquini** [comment]
It should be fixed now: if the openid of a new user is set by default to "openiduserXXX", then it is changed to "last-part-of-openid-XXX". It should only affect new users from CEDA, which has turned off their attribute exchange.
Also, I did not completely tested this since the CEDA IdP seems to be down at this time.

**Comment by LucaCinquini** [comment]
I now successfully tested this on the cog-cu-dev site: I logged in with my CEDA openid:

https://ceda.ac.uk/openid/Luca.Cinquini1

and I was assigned an account with username Luca.Cinquini1

Note that I had to fill in all required fields including first name, last name and email because the CEDA IdP does not release them.
