### ISSUE TITLE
"Forgot Password?" only works with local IDP

### ISSUE THREAD

**Issue by murphysj** [EarthSystemCoG/COG#1065]
WHO: Luca

Need to do something about this. Make it more clear, route folks to the correct IDP, or perhaps hide the link.

**Comment by LucaCinquini** [comment]
There have been extensive changes to this functionality so that now it works only for users with a local openid. If the openid is not local:
o If possible, the user is advised to issue the same request at the CoG site which issued the openid
o If no such CoG site is found, we make our best guess on where the user should go based on their openid.

**Comment by murphysj** [comment]
verified on dev-hydra. closing.
