### ISSUE TITLE
Modify how Node Widget is turned on

### ISSUE THREAD

**Issue by murphysj** [EarthSystemCoG/COG#1131]
WHO: Cecelia

a) Have it off by default
b) Put an option in the "update project page" to turn it on

**Comment by LucaCinquini** [comment]
Done. Note that the flag only controls the optional display in the project home page, the widget will never show up in the other project pages.
In the process, I have also inserted a limit of 80px on the vertical size of the widget, after which a scrollbar will appear.
Since this change involves a database migration, after pulling you'll have to issue:
python manage.py migrate.

**Comment by murphysj** [comment]
verified on cu test 
closing
