### ISSUE TITLE
Fix email content of openid reminder

### ISSUE THREAD

**Issue by LucaCinquini** [EarthSystemCoG/COG#1216]
Who: Katharina

Currently it sends one email for each OpenID but the number of OpenIDs per email are increasing because the message string is not cleared after it sends the mail. I think this can be confusing for users.

I see two options - both needs modifications in the code:
a) send one single OpenID per mail
b) send all OpenIDs in one mail

I think option b) is preferable.

**Comment by murphysj** [comment]
I am not sure I understand the issue here? Is this when folks hit the
openid reminder? How is more than one listed in the email?

On Thu, Jan 28, 2016 at 6:08 AM, Luca Cinquini <notifications@github.com>
wrote:

> Who: Katharina
>
> Currently it sends one email for each OpenID but the number of OpenIDs per
> email are increasing because the message string is not cleared after it
> sends the mail I think this can be confusing for users
>
> I see two options - both needs modifications in the code:
> a) send one single OpenID per mail
> b) send all OpenIDs in one mail
>
> I think option b) is preferable
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EarthSystemCoG/COG/issues/1216>.
>



-- 
******************************************
Sylvia Murphy
NESII/CIRES/NOAA Earth System Research Laboratory
325 Broadway, Boulder CO 80305
Time Zone: U.S. Mountain
Web: http://www.esrl.noaa.gov/nesii/
Email: sylvia.murphy@noaa.gov
Phone: 303-497-7753

**Comment by LucaCinquini** [comment]
This is because we do not require emails to be unique in the system (on purpose): many accounts can be associated with the same email.

**Comment by LucaCinquini** [comment]
Now when a user clicks on 'openid reminder', and enter their email, the system looks for ALL accounts at that CoG that are associated with that email, and for their corresponding open ids. It sends a single email to that address that contains all of the username/openid combinations, one per account.

**Comment by murphysj** [comment]
We will have to test this in production because cu dev does not have an ESGF IdP.

**Comment by murphysj** [comment]
FYI, I tested this in production after the release and it worked.
