### ISSUE TITLE
Make sure that on new installation that site_media subdirectories are created

### ISSUE THREAD

**Issue by murphysj** [EarthSystemCoG/COG#1270]
WHO: Sylvia
Found issue when we wiped out CU-Dev

drwxrwsr-x   3 nobody   web  4096 Jan 20 03:20 config
lrwxrwxrwx   1 luci0857 web    22 Oct  2  2014 docs -> ./projects/system_docs
drwxrwsr-x   3 nobody   web  4096 Sep  2  2014 img
drwxrwsr-x   3 nobody   web 20480 Mar 23 11:00 logos
drwxrwsr-x   2 nobody   web 12288 Jan  4 16:30 photos
drwsrwsr-x 178 nobody   web  4096 Mar 18 13:37 projects
lrwxrwxrwx   1 luci0857 web    24 Oct  2  2014 uploads -> ./projects/system_images

add photos. 

investigate why we need world writable on cu-dev but not the production system

**Comment by LucaCinquini** [comment]
It turns out that these two locations under $COG_CONFIG_DIR:

docs -> ./projects/system_docs
uploads -> ./projects/systyem_images

are directories where we store document and images that were uploaded a long time, before we adopted a new directory structure for storing resources under each project. So, they don't really have to be re-created every time CoG is installed. Hopefully, we will never again re-install CoG at CU or CU-DEV from scratch: if we do, we just need to keep those directories around and move them into the proper location.

I did verify that for a completely new install, the following directories are automatically created:

$COG_CONFIG_DIR/site_media/
$COG_CONFIG_DIR/site_media/logos/
$COG_CONFIG_DIR/site_media/photos/
$COG_CONFIG_DIR/site_media/projects/<project short name>/

**Comment by murphysj** [comment]
closing
