### ISSUE TITLE
Have full name of a project appear when you hover over the name in the Project Browser

### ISSUE THREAD

**Issue by murphysj** [EarthSystemCoG/COG#343]
WHO: Christiana
Benefits: All users
It is hard to know what a project acronym means.  If the full name of the project appeared on a hover it would make it easier to understand.

**Comment by LucaCinquini** [comment]
I implemented this starting from a JS tooltip plugin that I found here:

http://sixrevisions.com/tutorials/javascript_tutorial/create_lightweight_javascript_tooltip/

It is now functional but it needs some testing and styling. In particular:

o the tooltip color needs to be coordinated with the rest of the site. 
o the tooltip bottom image needs to be reversed so it points to the right
o IE must be checked since the positioning of the tooltip might be different

The code for the tooltip is contained within the two files:

toolstip/script.js
tooltip/style.css

that are included from right_column_css.html

Already merged into CSS branch.

**Comment by murphysj** [comment]
have you made tooltip part of the build? I reinstalled the dependencies and can not find tooltip in STATIC_URL

**Comment by murphysj** [comment]
styling this turned out to be MUCH harder than expected. 

The default tooltip relies on images. Those images are only grey and only point to the left. That would not work for us. 

It is easy to create a simple pop-up that is just a square rectangle or a rectangle with rounded corners.

I then tried to see if there was a way to create via CSS the little triangles that you see on these types of boxes. That was easy. 

Getting the triangle to connect to the dialog box required a full rewrite of the javascript display to be a table. Figuring out how javascript does tables, inserts text, replaces text extra was time consuming. 

We can now at least control things. We'll see what Cecelia wants now.

**Comment by murphysj** [comment]
Cecelia wanted 
1) the arrow towards the bottom
2) Background gray
3) Text white
4) 2px distance between Project Browser and start of the tp
5) "Full Name" removed
6) Extra padding on the left before the text

**Comment by murphysj** [comment]
verified on dev-hydra. closing.
