### ISSUE TITLE
Enable uploaded files to be automatic Resources

### ISSUE THREAD

**Issue by murphysj** [EarthSystemCoG/COG#346]
WHO: Sylvia
Benefits: All users

I am currently uploading files and then linking them as resources.  It would be nice if there was a checkbox on the file upload to turn the file URL into an automatic resource.

**Comment by murphysj** [comment]
Start with add resource and be able to have a URL or upload a file.

**Comment by LucaCinquini** [comment]
It turns out it's easier and makes more sense to start with the Doc form, since Doc are the primary objects. Now, when uploading a Doc, the user has the option of making it a Resource, choosing or creating a new destination folder.
Note that any change to the Doc name or description will automatically change the Resource title and description, respectively, and vice-versa.
Deleting the Doc will also automatically delete the Resource, since art that point the Resource becomes invalid (the URL won't work any more). On the other hand, deleting a Resource will NOT cause the underlying Doc to be deleted, since users may want to keep that file to be available for download, even if it is not listed as a Resource any more.

**Comment by murphysj** [comment]
verified on dev-hydra. closing.
