### ISSUE TITLE
Upgrade to latest version of Django

### ISSUE THREAD

**Issue by murphysj** [EarthSystemCoG/COG#979]
WHO: Luca

Will be intrusive

**Comment by LucaCinquini** [comment]
I always am.

On Jan 27, 2015, at 2:26 PM, Sylvia Murphy <notifications@github.com<mailto:notifications@github.com>> wrote:


WHO: Luca

Will be intrusive

**Comment by murphysj** [comment]
I just wanted to tell you in writing since I am too embarrassed to say it
in person.

On Tue, Jan 27, 2015 at 2:53 PM, Luca Cinquini <notifications@github.com>
wrote:

> I always am.
>
> On Jan 27, 2015, at 2:26 PM, Sylvia Murphy <notifications@github.com
> <mailto:notifications@github.com>> wrote:
>
>
> WHO: Luca
>
> Will be intrusive
>
> —
> Reply to this email directly or view it on GitHub<
> https://github.com/EarthSystemCoG/COG/issues/979>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EarthSystemCoG/COG/issues/979#issuecomment-71735605>.
>



-- 
******************************************
Sylvia Murphy
NESII/CIRES/NOAA Earth System Research Laboratory
325 Broadway, Boulder CO 80305
Time Zone: U.S. Mountain
Web: http://www.esrl.noaa.gov/nesii/
Email: sylvia.murphy@noaa.gov
Phone: 303-497-7753

**Comment by murphysj** [comment]
Luca reported that is was an issue that may require its own release. Moving out of 2.10.

**Comment by LucaCinquini** [comment]
Latest version is now 1.8.2

**Comment by murphysj** [comment]
Are you going to do a patch release with this?

On Thu, Jun 25, 2015 at 8:26 AM, Luca Cinquini <notifications@github.com>
wrote:

> Latest version is now 1.8.2
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EarthSystemCoG/COG/issues/979#issuecomment-115275425>.
>



-- 
******************************************
Sylvia Murphy
NESII/CIRES/NOAA Earth System Research Laboratory
325 Broadway, Boulder CO 80305
Time Zone: U.S. Mountain
Web: http://www.esrl.noaa.gov/nesii/
Email: sylvia.murphy@noaa.gov
Phone: 303-497-7753

**Comment by LucaCinquini** [comment]
Well, I wouldn’t call it a patch release since it’s a major effort. I created a 2.13 release that has pretty much just this upgrade, and am working on it…
thanks, L

On Jun 25, 2015, at 8:33 AM, Sylvia Murphy <notifications@github.com<mailto:notifications@github.com>> wrote:

Are you going to do a patch release with this?

On Thu, Jun 25, 2015 at 8:26 AM, Luca Cinquini <notifications@github.com<mailto:notifications@github.com>>
wrote:

> Latest version is now 1.8.2
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EarthSystemCoG/COG/issues/979#issuecomment-115275425>.
>



--
******************************************
Sylvia Murphy
NESII/CIRES/NOAA Earth System Research Laboratory
325 Broadway, Boulder CO 80305
Time Zone: U.S. Mountain
Web: http://www.esrl.noaa.gov/nesii/
Email: sylvia.murphy@noaa.gov<mailto:sylvia.murphy@noaa.gov>
Phone: 303-497-7753

**Comment by murphysj** [comment]
verified on dev-hydra. Closing.
